// Code generated by pigeon; DO NOT EDIT.

package parser

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"sync"
	"unicode"
	"unicode/utf8"
)

func toAnySlice(v any) ([]any, bool) {
	if v == nil {
		return nil, false
	}
	newV, ok := v.([]any)
	return newV, ok
}

var g = &grammar{
	rules: []*rule{
		{
			name: "Start",
			pos:  position{line: 14, col: 1, offset: 159},
			expr: &actionExpr{
				pos: position{line: 14, col: 10, offset: 168},
				run: (*parser).callonStart1,
				expr: &seqExpr{
					pos: position{line: 14, col: 10, offset: 168},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 14, col: 10, offset: 168},
							label: "top",
							expr: &ruleRefExpr{
								pos:  position{line: 14, col: 14, offset: 172},
								name: "Seq",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 14, col: 18, offset: 176},
							name: "EOF",
						},
					},
				},
			},
		},
		{
			name: "Seq",
			pos:  position{line: 19, col: 1, offset: 209},
			expr: &actionExpr{
				pos: position{line: 19, col: 8, offset: 216},
				run: (*parser).callonSeq1,
				expr: &labeledExpr{
					pos:   position{line: 19, col: 8, offset: 216},
					label: "v",
					expr: &choiceExpr{
						pos: position{line: 19, col: 11, offset: 219},
						alternatives: []any{
							&seqExpr{
								pos: position{line: 19, col: 11, offset: 219},
								exprs: []any{
									&choiceExpr{
										pos: position{line: 19, col: 13, offset: 221},
										alternatives: []any{
											&ruleRefExpr{
												pos:  position{line: 19, col: 13, offset: 221},
												name: "IfElse",
											},
											&ruleRefExpr{
												pos:  position{line: 19, col: 22, offset: 230},
												name: "If",
											},
											&ruleRefExpr{
												pos:  position{line: 19, col: 27, offset: 235},
												name: "For",
											},
											&ruleRefExpr{
												pos:  position{line: 19, col: 33, offset: 241},
												name: "TextBlock",
											},
											&ruleRefExpr{
												pos:  position{line: 19, col: 45, offset: 253},
												name: "Accessor",
											},
										},
									},
									&ruleRefExpr{
										pos:  position{line: 19, col: 56, offset: 264},
										name: "Seq",
									},
								},
							},
							&litMatcher{
								pos:        position{line: 19, col: 62, offset: 270},
								val:        "",
								ignoreCase: false,
								want:       "\"\"",
							},
						},
					},
				},
			},
		},
		{
			name: "IfElse",
			pos:  position{line: 33, col: 1, offset: 466},
			expr: &actionExpr{
				pos: position{line: 33, col: 11, offset: 476},
				run: (*parser).callonIfElse1,
				expr: &seqExpr{
					pos: position{line: 33, col: 11, offset: 476},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 33, col: 11, offset: 476},
							name: "S",
						},
						&litMatcher{
							pos:        position{line: 33, col: 13, offset: 478},
							val:        "if",
							ignoreCase: false,
							want:       "\"if\"",
						},
						&ruleRefExpr{
							pos:  position{line: 33, col: 18, offset: 483},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 33, col: 20, offset: 485},
							label: "cond",
							expr: &ruleRefExpr{
								pos:  position{line: 33, col: 25, offset: 490},
								name: "OrCondition",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 33, col: 37, offset: 502},
							name: "_",
						},
						&ruleRefExpr{
							pos:  position{line: 33, col: 39, offset: 504},
							name: "S",
						},
						&ruleRefExpr{
							pos:  position{line: 33, col: 41, offset: 506},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 33, col: 43, offset: 508},
							label: "tr",
							expr: &ruleRefExpr{
								pos:  position{line: 33, col: 46, offset: 511},
								name: "Seq",
							},
						},
						&labeledExpr{
							pos:   position{line: 33, col: 50, offset: 515},
							label: "os",
							expr: &oneOrMoreExpr{
								pos: position{line: 33, col: 53, offset: 518},
								expr: &seqExpr{
									pos: position{line: 33, col: 54, offset: 519},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 33, col: 54, offset: 519},
											name: "S",
										},
										&litMatcher{
											pos:        position{line: 33, col: 56, offset: 521},
											val:        "else",
											ignoreCase: false,
											want:       "\"else\"",
										},
										&ruleRefExpr{
											pos:  position{line: 33, col: 63, offset: 528},
											name: "_",
										},
										&litMatcher{
											pos:        position{line: 33, col: 65, offset: 530},
											val:        "if",
											ignoreCase: false,
											want:       "\"if\"",
										},
										&ruleRefExpr{
											pos:  position{line: 33, col: 70, offset: 535},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 33, col: 72, offset: 537},
											name: "OrCondition",
										},
										&ruleRefExpr{
											pos:  position{line: 33, col: 84, offset: 549},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 33, col: 86, offset: 551},
											name: "S",
										},
										&ruleRefExpr{
											pos:  position{line: 33, col: 88, offset: 553},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 33, col: 90, offset: 555},
											name: "Seq",
										},
										&ruleRefExpr{
											pos:  position{line: 33, col: 94, offset: 559},
											name: "_",
										},
									},
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 33, col: 98, offset: 563},
							label: "el",
							expr: &zeroOrOneExpr{
								pos: position{line: 33, col: 101, offset: 566},
								expr: &seqExpr{
									pos: position{line: 33, col: 102, offset: 567},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 33, col: 102, offset: 567},
											name: "S",
										},
										&ruleRefExpr{
											pos:  position{line: 33, col: 104, offset: 569},
											name: "_",
										},
										&litMatcher{
											pos:        position{line: 33, col: 106, offset: 571},
											val:        "else",
											ignoreCase: false,
											want:       "\"else\"",
										},
										&ruleRefExpr{
											pos:  position{line: 33, col: 113, offset: 578},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 33, col: 115, offset: 580},
											name: "S",
										},
										&ruleRefExpr{
											pos:  position{line: 33, col: 118, offset: 583},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 33, col: 120, offset: 585},
											name: "Seq",
										},
										&ruleRefExpr{
											pos:  position{line: 33, col: 124, offset: 589},
											name: "_",
										},
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 33, col: 129, offset: 594},
							name: "S",
						},
						&litMatcher{
							pos:        position{line: 33, col: 131, offset: 596},
							val:        "end",
							ignoreCase: false,
							want:       "\"end\"",
						},
						&ruleRefExpr{
							pos:  position{line: 33, col: 137, offset: 602},
							name: "S",
						},
					},
				},
			},
		},
		{
			name: "If",
			pos:  position{line: 60, col: 1, offset: 1306},
			expr: &actionExpr{
				pos: position{line: 60, col: 7, offset: 1312},
				run: (*parser).callonIf1,
				expr: &seqExpr{
					pos: position{line: 60, col: 7, offset: 1312},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 60, col: 7, offset: 1312},
							name: "S",
						},
						&litMatcher{
							pos:        position{line: 60, col: 9, offset: 1314},
							val:        "if",
							ignoreCase: false,
							want:       "\"if\"",
						},
						&ruleRefExpr{
							pos:  position{line: 60, col: 14, offset: 1319},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 60, col: 16, offset: 1321},
							label: "cond",
							expr: &ruleRefExpr{
								pos:  position{line: 60, col: 21, offset: 1326},
								name: "OrCondition",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 60, col: 33, offset: 1338},
							name: "_",
						},
						&ruleRefExpr{
							pos:  position{line: 60, col: 35, offset: 1340},
							name: "S",
						},
						&ruleRefExpr{
							pos:  position{line: 60, col: 37, offset: 1342},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 60, col: 39, offset: 1344},
							label: "tr",
							expr: &ruleRefExpr{
								pos:  position{line: 60, col: 42, offset: 1347},
								name: "Seq",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 60, col: 46, offset: 1351},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 60, col: 48, offset: 1353},
							label: "f",
							expr: &zeroOrOneExpr{
								pos: position{line: 60, col: 50, offset: 1355},
								expr: &seqExpr{
									pos: position{line: 60, col: 51, offset: 1356},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 60, col: 51, offset: 1356},
											name: "S",
										},
										&litMatcher{
											pos:        position{line: 60, col: 53, offset: 1358},
											val:        "else",
											ignoreCase: false,
											want:       "\"else\"",
										},
										&ruleRefExpr{
											pos:  position{line: 60, col: 60, offset: 1365},
											name: "S",
										},
										&ruleRefExpr{
											pos:  position{line: 60, col: 62, offset: 1367},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 60, col: 64, offset: 1369},
											name: "Seq",
										},
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 60, col: 70, offset: 1375},
							name: "S",
						},
						&litMatcher{
							pos:        position{line: 60, col: 72, offset: 1377},
							val:        "end",
							ignoreCase: false,
							want:       "\"end\"",
						},
						&ruleRefExpr{
							pos:  position{line: 60, col: 78, offset: 1383},
							name: "S",
						},
					},
				},
			},
		},
		{
			name: "For",
			pos:  position{line: 75, col: 1, offset: 1744},
			expr: &actionExpr{
				pos: position{line: 75, col: 8, offset: 1751},
				run: (*parser).callonFor1,
				expr: &seqExpr{
					pos: position{line: 75, col: 8, offset: 1751},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 75, col: 8, offset: 1751},
							name: "S",
						},
						&litMatcher{
							pos:        position{line: 75, col: 10, offset: 1753},
							val:        "for",
							ignoreCase: false,
							want:       "\"for\"",
						},
						&ruleRefExpr{
							pos:  position{line: 75, col: 16, offset: 1759},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 75, col: 18, offset: 1761},
							label: "vars",
							expr: &ruleRefExpr{
								pos:  position{line: 75, col: 23, offset: 1766},
								name: "ForVars",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 75, col: 31, offset: 1774},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 75, col: 33, offset: 1776},
							val:        "=",
							ignoreCase: false,
							want:       "\"=\"",
						},
						&ruleRefExpr{
							pos:  position{line: 75, col: 37, offset: 1780},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 75, col: 39, offset: 1782},
							label: "t",
							expr: &choiceExpr{
								pos: position{line: 75, col: 42, offset: 1785},
								alternatives: []any{
									&litMatcher{
										pos:        position{line: 75, col: 42, offset: 1785},
										val:        "range",
										ignoreCase: false,
										want:       "\"range\"",
									},
									&litMatcher{
										pos:        position{line: 75, col: 52, offset: 1795},
										val:        "props",
										ignoreCase: false,
										want:       "\"props\"",
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 75, col: 61, offset: 1804},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 75, col: 63, offset: 1806},
							label: "p",
							expr: &ruleRefExpr{
								pos:  position{line: 75, col: 65, offset: 1808},
								name: "AccessPattern",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 75, col: 79, offset: 1822},
							name: "_",
						},
						&ruleRefExpr{
							pos:  position{line: 75, col: 81, offset: 1824},
							name: "S",
						},
						&ruleRefExpr{
							pos:  position{line: 75, col: 83, offset: 1826},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 75, col: 85, offset: 1828},
							label: "l",
							expr: &ruleRefExpr{
								pos:  position{line: 75, col: 87, offset: 1830},
								name: "Seq",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 75, col: 91, offset: 1834},
							name: "S",
						},
						&litMatcher{
							pos:        position{line: 75, col: 93, offset: 1836},
							val:        "end",
							ignoreCase: false,
							want:       "\"end\"",
						},
						&ruleRefExpr{
							pos:  position{line: 75, col: 99, offset: 1842},
							name: "S",
						},
					},
				},
			},
		},
		{
			name: "ForVars",
			pos:  position{line: 85, col: 1, offset: 2149},
			expr: &actionExpr{
				pos: position{line: 85, col: 12, offset: 2160},
				run: (*parser).callonForVars1,
				expr: &seqExpr{
					pos: position{line: 85, col: 12, offset: 2160},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 85, col: 12, offset: 2160},
							label: "v1",
							expr: &ruleRefExpr{
								pos:  position{line: 85, col: 15, offset: 2163},
								name: "VarName",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 85, col: 23, offset: 2171},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 85, col: 25, offset: 2173},
							val:        ",",
							ignoreCase: false,
							want:       "\",\"",
						},
						&ruleRefExpr{
							pos:  position{line: 85, col: 29, offset: 2177},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 85, col: 31, offset: 2179},
							label: "v2",
							expr: &ruleRefExpr{
								pos:  position{line: 85, col: 34, offset: 2182},
								name: "VarName",
							},
						},
					},
				},
			},
		},
		{
			name: "VarName",
			pos:  position{line: 91, col: 1, offset: 2287},
			expr: &actionExpr{
				pos: position{line: 91, col: 12, offset: 2298},
				run: (*parser).callonVarName1,
				expr: &oneOrMoreExpr{
					pos: position{line: 91, col: 12, offset: 2298},
					expr: &charClassMatcher{
						pos:        position{line: 91, col: 12, offset: 2298},
						val:        "[a-zA-Z]",
						ranges:     []rune{'a', 'z', 'A', 'Z'},
						ignoreCase: false,
						inverted:   false,
					},
				},
			},
		},
		{
			name: "Accessor",
			pos:  position{line: 97, col: 1, offset: 2368},
			expr: &actionExpr{
				pos: position{line: 97, col: 13, offset: 2380},
				run: (*parser).callonAccessor1,
				expr: &seqExpr{
					pos: position{line: 97, col: 13, offset: 2380},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 97, col: 13, offset: 2380},
							name: "S",
						},
						&labeledExpr{
							pos:   position{line: 97, col: 15, offset: 2382},
							label: "t",
							expr: &ruleRefExpr{
								pos:  position{line: 97, col: 17, offset: 2384},
								name: "AccessPattern",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 97, col: 31, offset: 2398},
							name: "S",
						},
					},
				},
			},
		},
		{
			name: "TextBlock",
			pos:  position{line: 105, col: 1, offset: 2534},
			expr: &actionExpr{
				pos: position{line: 105, col: 14, offset: 2547},
				run: (*parser).callonTextBlock1,
				expr: &labeledExpr{
					pos:   position{line: 105, col: 14, offset: 2547},
					label: "t",
					expr: &ruleRefExpr{
						pos:  position{line: 105, col: 16, offset: 2549},
						name: "Text",
					},
				},
			},
		},
		{
			name: "OrCondition",
			pos:  position{line: 112, col: 1, offset: 2669},
			expr: &actionExpr{
				pos: position{line: 112, col: 16, offset: 2684},
				run: (*parser).callonOrCondition1,
				expr: &seqExpr{
					pos: position{line: 112, col: 16, offset: 2684},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 112, col: 16, offset: 2684},
							label: "base",
							expr: &ruleRefExpr{
								pos:  position{line: 112, col: 21, offset: 2689},
								name: "AndCondition",
							},
						},
						&labeledExpr{
							pos:   position{line: 112, col: 34, offset: 2702},
							label: "os",
							expr: &zeroOrMoreExpr{
								pos: position{line: 112, col: 37, offset: 2705},
								expr: &seqExpr{
									pos: position{line: 112, col: 39, offset: 2707},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 112, col: 39, offset: 2707},
											name: "_",
										},
										&litMatcher{
											pos:        position{line: 112, col: 41, offset: 2709},
											val:        "or",
											ignoreCase: false,
											want:       "\"or\"",
										},
										&ruleRefExpr{
											pos:  position{line: 112, col: 47, offset: 2715},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 112, col: 49, offset: 2717},
											name: "AndCondition",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "AndCondition",
			pos:  position{line: 136, col: 1, offset: 3112},
			expr: &actionExpr{
				pos: position{line: 136, col: 17, offset: 3128},
				run: (*parser).callonAndCondition1,
				expr: &seqExpr{
					pos: position{line: 136, col: 17, offset: 3128},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 136, col: 17, offset: 3128},
							label: "base",
							expr: &ruleRefExpr{
								pos:  position{line: 136, col: 22, offset: 3133},
								name: "Condition",
							},
						},
						&labeledExpr{
							pos:   position{line: 136, col: 32, offset: 3143},
							label: "os",
							expr: &zeroOrMoreExpr{
								pos: position{line: 136, col: 35, offset: 3146},
								expr: &seqExpr{
									pos: position{line: 136, col: 37, offset: 3148},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 136, col: 37, offset: 3148},
											name: "_",
										},
										&litMatcher{
											pos:        position{line: 136, col: 39, offset: 3150},
											val:        "and",
											ignoreCase: false,
											want:       "\"and\"",
										},
										&ruleRefExpr{
											pos:  position{line: 136, col: 45, offset: 3156},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 136, col: 48, offset: 3159},
											name: "Condition",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Condition",
			pos:  position{line: 158, col: 1, offset: 3548},
			expr: &actionExpr{
				pos: position{line: 158, col: 14, offset: 3561},
				run: (*parser).callonCondition1,
				expr: &labeledExpr{
					pos:   position{line: 158, col: 14, offset: 3561},
					label: "e",
					expr: &choiceExpr{
						pos: position{line: 158, col: 18, offset: 3565},
						alternatives: []any{
							&ruleRefExpr{
								pos:  position{line: 158, col: 18, offset: 3565},
								name: "OfType",
							},
							&ruleRefExpr{
								pos:  position{line: 158, col: 27, offset: 3574},
								name: "Exists",
							},
							&ruleRefExpr{
								pos:  position{line: 158, col: 36, offset: 3583},
								name: "FromElements",
							},
							&seqExpr{
								pos: position{line: 158, col: 51, offset: 3598},
								exprs: []any{
									&zeroOrOneExpr{
										pos: position{line: 158, col: 51, offset: 3598},
										expr: &litMatcher{
											pos:        position{line: 158, col: 52, offset: 3599},
											val:        "!",
											ignoreCase: false,
											want:       "\"!\"",
										},
									},
									&ruleRefExpr{
										pos:  position{line: 158, col: 58, offset: 3605},
										name: "GroupedCondition",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "OfType",
			pos:  position{line: 177, col: 1, offset: 3872},
			expr: &actionExpr{
				pos: position{line: 177, col: 11, offset: 3882},
				run: (*parser).callonOfType1,
				expr: &seqExpr{
					pos: position{line: 177, col: 11, offset: 3882},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 177, col: 11, offset: 3882},
							label: "p",
							expr: &ruleRefExpr{
								pos:  position{line: 177, col: 13, offset: 3884},
								name: "AccessPattern",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 177, col: 27, offset: 3898},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 177, col: 29, offset: 3900},
							val:        "isa",
							ignoreCase: false,
							want:       "\"isa\"",
						},
						&ruleRefExpr{
							pos:  position{line: 177, col: 35, offset: 3906},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 177, col: 37, offset: 3908},
							label: "e",
							expr: &ruleRefExpr{
								pos:  position{line: 177, col: 39, offset: 3910},
								name: "TypeExpression",
							},
						},
					},
				},
			},
		},
		{
			name: "TypeExpression",
			pos:  position{line: 184, col: 1, offset: 4087},
			expr: &choiceExpr{
				pos: position{line: 184, col: 19, offset: 4105},
				alternatives: []any{
					&litMatcher{
						pos:        position{line: 184, col: 19, offset: 4105},
						val:        "array",
						ignoreCase: false,
						want:       "\"array\"",
					},
					&litMatcher{
						pos:        position{line: 184, col: 29, offset: 4115},
						val:        "object",
						ignoreCase: false,
						want:       "\"object\"",
					},
					&litMatcher{
						pos:        position{line: 184, col: 40, offset: 4126},
						val:        "number",
						ignoreCase: false,
						want:       "\"number\"",
					},
					&litMatcher{
						pos:        position{line: 184, col: 51, offset: 4137},
						val:        "string",
						ignoreCase: false,
						want:       "\"string\"",
					},
					&litMatcher{
						pos:        position{line: 184, col: 62, offset: 4148},
						val:        "bool",
						ignoreCase: false,
						want:       "\"bool\"",
					},
				},
			},
		},
		{
			name: "Exists",
			pos:  position{line: 186, col: 1, offset: 4159},
			expr: &actionExpr{
				pos: position{line: 186, col: 11, offset: 4169},
				run: (*parser).callonExists1,
				expr: &seqExpr{
					pos: position{line: 186, col: 11, offset: 4169},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 186, col: 11, offset: 4169},
							val:        "exists",
							ignoreCase: false,
							want:       "\"exists\"",
						},
						&ruleRefExpr{
							pos:  position{line: 186, col: 20, offset: 4178},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 186, col: 22, offset: 4180},
							label: "p",
							expr: &ruleRefExpr{
								pos:  position{line: 186, col: 24, offset: 4182},
								name: "AccessPattern",
							},
						},
					},
				},
			},
		},
		{
			name: "GroupedCondition",
			pos:  position{line: 192, col: 1, offset: 4281},
			expr: &actionExpr{
				pos: position{line: 192, col: 21, offset: 4301},
				run: (*parser).callonGroupedCondition1,
				expr: &seqExpr{
					pos: position{line: 192, col: 21, offset: 4301},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 192, col: 21, offset: 4301},
							val:        "(",
							ignoreCase: false,
							want:       "\"(\"",
						},
						&ruleRefExpr{
							pos:  position{line: 192, col: 25, offset: 4305},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 192, col: 27, offset: 4307},
							label: "cond",
							expr: &ruleRefExpr{
								pos:  position{line: 192, col: 32, offset: 4312},
								name: "OrCondition",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 192, col: 44, offset: 4324},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 192, col: 46, offset: 4326},
							val:        ")",
							ignoreCase: false,
							want:       "\")\"",
						},
					},
				},
			},
		},
		{
			name: "FromElements",
			pos:  position{line: 196, col: 1, offset: 4358},
			expr: &actionExpr{
				pos: position{line: 196, col: 17, offset: 4374},
				run: (*parser).callonFromElements1,
				expr: &labeledExpr{
					pos:   position{line: 196, col: 17, offset: 4374},
					label: "e",
					expr: &choiceExpr{
						pos: position{line: 196, col: 20, offset: 4377},
						alternatives: []any{
							&seqExpr{
								pos: position{line: 196, col: 20, offset: 4377},
								exprs: []any{
									&ruleRefExpr{
										pos:  position{line: 196, col: 20, offset: 4377},
										name: "ConditionElement",
									},
									&ruleRefExpr{
										pos:  position{line: 196, col: 37, offset: 4394},
										name: "_",
									},
									&ruleRefExpr{
										pos:  position{line: 196, col: 39, offset: 4396},
										name: "Operator",
									},
									&ruleRefExpr{
										pos:  position{line: 196, col: 48, offset: 4405},
										name: "_",
									},
									&ruleRefExpr{
										pos:  position{line: 196, col: 50, offset: 4407},
										name: "ConditionElement",
									},
								},
							},
							&seqExpr{
								pos: position{line: 196, col: 69, offset: 4426},
								exprs: []any{
									&zeroOrOneExpr{
										pos: position{line: 196, col: 70, offset: 4427},
										expr: &litMatcher{
											pos:        position{line: 196, col: 70, offset: 4427},
											val:        "!",
											ignoreCase: false,
											want:       "\"!\"",
										},
									},
									&ruleRefExpr{
										pos:  position{line: 196, col: 76, offset: 4433},
										name: "ConditionElement",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "ConditionElement",
			pos:  position{line: 230, col: 1, offset: 5166},
			expr: &actionExpr{
				pos: position{line: 230, col: 21, offset: 5186},
				run: (*parser).callonConditionElement1,
				expr: &labeledExpr{
					pos:   position{line: 230, col: 21, offset: 5186},
					label: "e",
					expr: &choiceExpr{
						pos: position{line: 230, col: 24, offset: 5189},
						alternatives: []any{
							&ruleRefExpr{
								pos:  position{line: 230, col: 24, offset: 5189},
								name: "Constant",
							},
							&ruleRefExpr{
								pos:  position{line: 230, col: 35, offset: 5200},
								name: "AccessElement",
							},
						},
					},
				},
			},
		},
		{
			name: "Operator",
			pos:  position{line: 235, col: 1, offset: 5242},
			expr: &choiceExpr{
				pos: position{line: 235, col: 13, offset: 5254},
				alternatives: []any{
					&litMatcher{
						pos:        position{line: 235, col: 13, offset: 5254},
						val:        "=",
						ignoreCase: false,
						want:       "\"=\"",
					},
					&litMatcher{
						pos:        position{line: 235, col: 19, offset: 5260},
						val:        "<=",
						ignoreCase: false,
						want:       "\"<=\"",
					},
					&litMatcher{
						pos:        position{line: 235, col: 26, offset: 5267},
						val:        ">=",
						ignoreCase: false,
						want:       "\">=\"",
					},
					&litMatcher{
						pos:        position{line: 235, col: 33, offset: 5274},
						val:        "<",
						ignoreCase: false,
						want:       "\"<\"",
					},
					&litMatcher{
						pos:        position{line: 235, col: 39, offset: 5280},
						val:        ">",
						ignoreCase: false,
						want:       "\">\"",
					},
					&litMatcher{
						pos:        position{line: 235, col: 45, offset: 5286},
						val:        "!=",
						ignoreCase: false,
						want:       "\"!=\"",
					},
				},
			},
		},
		{
			name: "Constant",
			pos:  position{line: 237, col: 1, offset: 5294},
			expr: &actionExpr{
				pos: position{line: 237, col: 13, offset: 5306},
				run: (*parser).callonConstant1,
				expr: &choiceExpr{
					pos: position{line: 237, col: 14, offset: 5307},
					alternatives: []any{
						&seqExpr{
							pos: position{line: 237, col: 14, offset: 5307},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 237, col: 14, offset: 5307},
									val:        "\"",
									ignoreCase: false,
									want:       "\"\\\"\"",
								},
								&oneOrMoreExpr{
									pos: position{line: 237, col: 18, offset: 5311},
									expr: &charClassMatcher{
										pos:        position{line: 237, col: 18, offset: 5311},
										val:        "[^$\"()]",
										chars:      []rune{'$', '"', '(', ')'},
										ignoreCase: false,
										inverted:   true,
									},
								},
								&litMatcher{
									pos:        position{line: 237, col: 27, offset: 5320},
									val:        "\"",
									ignoreCase: false,
									want:       "\"\\\"\"",
								},
							},
						},
						&seqExpr{
							pos: position{line: 237, col: 33, offset: 5326},
							exprs: []any{
								&zeroOrOneExpr{
									pos: position{line: 237, col: 33, offset: 5326},
									expr: &litMatcher{
										pos:        position{line: 237, col: 33, offset: 5326},
										val:        "-",
										ignoreCase: false,
										want:       "\"-\"",
									},
								},
								&oneOrMoreExpr{
									pos: position{line: 237, col: 38, offset: 5331},
									expr: &charClassMatcher{
										pos:        position{line: 237, col: 38, offset: 5331},
										val:        "[0-9]",
										ranges:     []rune{'0', '9'},
										ignoreCase: false,
										inverted:   false,
									},
								},
								&zeroOrOneExpr{
									pos: position{line: 237, col: 44, offset: 5337},
									expr: &seqExpr{
										pos: position{line: 237, col: 45, offset: 5338},
										exprs: []any{
											&litMatcher{
												pos:        position{line: 237, col: 45, offset: 5338},
												val:        ".",
												ignoreCase: false,
												want:       "\".\"",
											},
											&oneOrMoreExpr{
												pos: position{line: 237, col: 49, offset: 5342},
												expr: &charClassMatcher{
													pos:        position{line: 237, col: 49, offset: 5342},
													val:        "[0-9]",
													ranges:     []rune{'0', '9'},
													ignoreCase: false,
													inverted:   false,
												},
											},
										},
									},
								},
							},
						},
						&litMatcher{
							pos:        position{line: 237, col: 60, offset: 5353},
							val:        "true",
							ignoreCase: false,
							want:       "\"true\"",
						},
						&litMatcher{
							pos:        position{line: 237, col: 69, offset: 5362},
							val:        "false",
							ignoreCase: false,
							want:       "\"false\"",
						},
					},
				},
			},
		},
		{
			name: "AccessElement",
			pos:  position{line: 248, col: 1, offset: 5548},
			expr: &actionExpr{
				pos: position{line: 248, col: 18, offset: 5565},
				run: (*parser).callonAccessElement1,
				expr: &labeledExpr{
					pos:   position{line: 248, col: 18, offset: 5565},
					label: "t",
					expr: &ruleRefExpr{
						pos:  position{line: 248, col: 20, offset: 5567},
						name: "AccessPattern",
					},
				},
			},
		},
		{
			name: "AccessPattern",
			pos:  position{line: 253, col: 1, offset: 5663},
			expr: &actionExpr{
				pos: position{line: 253, col: 18, offset: 5680},
				run: (*parser).callonAccessPattern1,
				expr: &seqExpr{
					pos: position{line: 253, col: 18, offset: 5680},
					exprs: []any{
						&notExpr{
							pos: position{line: 253, col: 18, offset: 5680},
							expr: &choiceExpr{
								pos: position{line: 253, col: 20, offset: 5682},
								alternatives: []any{
									&ruleRefExpr{
										pos:  position{line: 253, col: 20, offset: 5682},
										name: "Special",
									},
									&ruleRefExpr{
										pos:  position{line: 253, col: 30, offset: 5692},
										name: "S",
									},
								},
							},
						},
						&oneOrMoreExpr{
							pos: position{line: 253, col: 33, offset: 5695},
							expr: &choiceExpr{
								pos: position{line: 253, col: 34, offset: 5696},
								alternatives: []any{
									&charClassMatcher{
										pos:        position{line: 253, col: 34, offset: 5696},
										val:        "[a-zA-Z0-9]",
										ranges:     []rune{'a', 'z', 'A', 'Z', '0', '9'},
										ignoreCase: false,
										inverted:   false,
									},
									&litMatcher{
										pos:        position{line: 253, col: 48, offset: 5710},
										val:        "->",
										ignoreCase: false,
										want:       "\"->\"",
									},
									&litMatcher{
										pos:        position{line: 253, col: 55, offset: 5717},
										val:        "[",
										ignoreCase: false,
										want:       "\"[\"",
									},
									&litMatcher{
										pos:        position{line: 253, col: 61, offset: 5723},
										val:        "]",
										ignoreCase: false,
										want:       "\"]\"",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Text",
			pos:  position{line: 258, col: 1, offset: 5781},
			expr: &actionExpr{
				pos: position{line: 258, col: 9, offset: 5789},
				run: (*parser).callonText1,
				expr: &oneOrMoreExpr{
					pos: position{line: 258, col: 9, offset: 5789},
					expr: &charClassMatcher{
						pos:        position{line: 258, col: 9, offset: 5789},
						val:        "[^$]",
						chars:      []rune{'$'},
						ignoreCase: false,
						inverted:   true,
					},
				},
			},
		},
		{
			name: "Special",
			pos:  position{line: 263, col: 1, offset: 5849},
			expr: &choiceExpr{
				pos: position{line: 263, col: 12, offset: 5860},
				alternatives: []any{
					&litMatcher{
						pos:        position{line: 263, col: 12, offset: 5860},
						val:        "for",
						ignoreCase: false,
						want:       "\"for\"",
					},
					&litMatcher{
						pos:        position{line: 263, col: 20, offset: 5868},
						val:        "if",
						ignoreCase: false,
						want:       "\"if\"",
					},
					&litMatcher{
						pos:        position{line: 263, col: 27, offset: 5875},
						val:        "range",
						ignoreCase: false,
						want:       "\"range\"",
					},
					&litMatcher{
						pos:        position{line: 263, col: 37, offset: 5885},
						val:        "props",
						ignoreCase: false,
						want:       "\"props\"",
					},
					&litMatcher{
						pos:        position{line: 263, col: 47, offset: 5895},
						val:        "exists",
						ignoreCase: false,
						want:       "\"exists\"",
					},
					&litMatcher{
						pos:        position{line: 263, col: 58, offset: 5906},
						val:        "end",
						ignoreCase: false,
						want:       "\"end\"",
					},
					&litMatcher{
						pos:        position{line: 263, col: 66, offset: 5914},
						val:        "else",
						ignoreCase: false,
						want:       "\"else\"",
					},
				},
			},
		},
		{
			name: "S",
			pos:  position{line: 265, col: 1, offset: 5925},
			expr: &litMatcher{
				pos:        position{line: 265, col: 6, offset: 5930},
				val:        "$",
				ignoreCase: false,
				want:       "\"$\"",
			},
		},
		{
			name:        "_",
			displayName: "\"whitespace\"",
			pos:         position{line: 267, col: 1, offset: 5937},
			expr: &zeroOrMoreExpr{
				pos: position{line: 267, col: 19, offset: 5955},
				expr: &charClassMatcher{
					pos:        position{line: 267, col: 19, offset: 5955},
					val:        "[ \\t\\r\\n]",
					chars:      []rune{' ', '\t', '\r', '\n'},
					ignoreCase: false,
					inverted:   false,
				},
			},
		},
		{
			name: "EOF",
			pos:  position{line: 269, col: 1, offset: 5969},
			expr: &notExpr{
				pos: position{line: 269, col: 8, offset: 5976},
				expr: &anyMatcher{
					line: 269, col: 9, offset: 5977,
				},
			},
		},
	},
}

func (c *current) onStart1(top any) (any, error) {

	return top, nil
}

func (p *parser) callonStart1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onStart1(stack["top"])
}

func (c *current) onSeq1(v any) (any, error) {

	vals, ok := toAnySlice(v)
	if !ok {
		return nil, nil
	} else {
		left, _ := vals[0].(node)
		right, _ := vals[1].(node)

		left.setNext(right)

		return left, nil
	}
}

func (p *parser) callonSeq1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSeq1(stack["v"])
}

func (c *current) onIfElse1(cond, tr, os, el any) (any, error) {

	other, _ := toAnySlice(os)
	topCondition, _ := cond.(condition)
	topTrue, _ := tr.(node)

	top := &ifNode{condition: topCondition, trueClause: topTrue, baseNode: baseNode{child: nil}}
	toRet := top

	for _, elseClause := range other {
		elseClauseElems, _ := toAnySlice(elseClause)
		elseCondition, _ := elseClauseElems[5].(condition)
		elseTrue, _ := elseClauseElems[9].(node)
		elseNode := &ifNode{condition: elseCondition, trueClause: elseTrue, baseNode: baseNode{child: nil}}
		top.falseClause = elseNode
		top = elseNode
	}

	if el != nil {
		elems, _ := toAnySlice(el)
		falseClause, _ := elems[6].(node)
		top.falseClause = falseClause
	}

	return toRet, nil

}

func (p *parser) callonIfElse1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIfElse1(stack["cond"], stack["tr"], stack["os"], stack["el"])
}

func (c *current) onIf1(cond, tr, f any) (any, error) {

	// condition, _ := (cond.c.string)
	condition := cond.(condition)
	trueClause, _ := tr.(node)
	var falseClause node

	if f != nil {
		vals, _ := toAnySlice(f)
		falseClause, _ = vals[4].(node)
	}

	node := ifNode{condition: condition, trueClause: trueClause, falseClause: falseClause, baseNode: baseNode{child: nil}}
	return &node, nil
}

func (p *parser) callonIf1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIf1(stack["cond"], stack["tr"], stack["f"])
}

func (c *current) onFor1(vars, t, p, l any) (any, error) {

	stringVars, _ := vars.([]string)
	loop, _ := l.(node)
	forT := string(t.([]byte))
	pattern, _ := p.(string)

	foraa := forNode{forType: forT == "range", itemName: stringVars[1], indexName: stringVars[0], pattern: pattern, loop: loop, baseNode: baseNode{child: nil}}
	return &foraa, nil
}

func (p *parser) callonFor1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFor1(stack["vars"], stack["t"], stack["p"], stack["l"])
}

func (c *current) onForVars1(v1, v2 any) (any, error) {

	vstr1, _ := v1.(string)
	vstr2, _ := v2.(string)
	return []string{vstr1, vstr2}, nil
}

func (p *parser) callonForVars1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onForVars1(stack["v1"], stack["v2"])
}

func (c *current) onVarName1() (any, error) {

	varName := string(c.text)
	return varName, nil
}

func (p *parser) callonVarName1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onVarName1()
}

func (c *current) onAccessor1(t any) (any, error) {

	pattern := t.(string)

	node := accessNode{accessPattern: pattern, baseNode: baseNode{child: nil}}
	return &node, nil
}

func (p *parser) callonAccessor1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAccessor1(stack["t"])
}

func (c *current) onTextBlock1(t any) (any, error) {

	text := t.(string)
	node := textNode{text: text, baseNode: baseNode{child: nil}}
	return &node, nil
}

func (p *parser) callonTextBlock1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTextBlock1(stack["t"])
}

func (c *current) onOrCondition1(base, os any) (any, error) {

	baseCondition, _ := base.(condition)
	others, _ := toAnySlice(os)

	if others == nil {
		return baseCondition, nil
	}

	curr := baseCondition

	for _, other := range others {
		components, _ := toAnySlice(other)
		condition, _ := components[3].(condition)
		top := orCondition{left: curr, right: condition}
		curr = top
	}

	return curr, nil

}

func (p *parser) callonOrCondition1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOrCondition1(stack["base"], stack["os"])
}

func (c *current) onAndCondition1(base, os any) (any, error) {

	baseCondition, _ := base.(condition)
	others, _ := toAnySlice(os)

	if others == nil {
		return baseCondition, nil
	}

	curr := baseCondition

	for _, other := range others {
		components, _ := toAnySlice(other)
		condition, _ := components[3].(condition)
		top := andCondition{left: curr, right: condition}
		curr = top
	}

	return curr, nil

}

func (p *parser) callonAndCondition1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAndCondition1(stack["base"], stack["os"])
}

func (c *current) onCondition1(e any) (any, error) {

	elems, isGroup := toAnySlice(e)

	if !isGroup {
		return e, nil
	}

	isNegated := elems[0] != nil
	cond, _ := elems[1].(condition)

	if isNegated {
		return negatedCondition{toNegate: cond}, nil
	}

	return cond, nil

}

func (p *parser) callonCondition1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCondition1(stack["e"])
}

func (c *current) onOfType1(p, e any) (any, error) {

	elemType, _ := e.([]byte)
	strType := string(elemType)
	pattern, _ := p.(string)
	return ofType{pattern: pattern, typeOf: convertType(strType)}, nil
}

func (p *parser) callonOfType1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOfType1(stack["p"], stack["e"])
}

func (c *current) onExists1(p any) (any, error) {

	pattern, _ := p.(string)
	return existsCondition{pattern: pattern}, nil
}

func (p *parser) callonExists1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onExists1(stack["p"])
}

func (c *current) onGroupedCondition1(cond any) (any, error) {

	return cond, nil
}

func (p *parser) callonGroupedCondition1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onGroupedCondition1(stack["cond"])
}

func (c *current) onFromElements1(e any) (any, error) {

	elems, _ := toAnySlice(e)

	isOperation := len(elems) == 5

	if isOperation {
		left, _ := elems[0].(element)
		right, _ := elems[4].(element)
		operator, _ := elems[2].([]uint8)
		return operatorCondition{left: left, right: right, operator: convertOperator(string(operator))}, nil
	}

	isElem := len(elems) == 2

	if isElem {
		elem, _ := elems[1].(element)
		elemCondition := singleCondition{element: elem}
		if elems[0] == nil {
			return elemCondition, nil
		} else {
			return negatedCondition{toNegate: elemCondition}, nil
		}

	}

	condition, isCondition := e.(condition)

	if isCondition {
		return condition, nil
	}

	return nil, errors.New("Invalid condition")
}

func (p *parser) callonFromElements1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFromElements1(stack["e"])
}

func (c *current) onConditionElement1(e any) (any, error) {

	return e, nil
}

func (p *parser) callonConditionElement1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onConditionElement1(stack["e"])
}

func (c *current) onConstant1() (any, error) {

	text := string(c.text)
	val, tpe, err := textToElem(text)
	if err != nil {
		return "", err
	}

	return constantElement{constant: val, constType: tpe}, nil

}

func (p *parser) callonConstant1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onConstant1()
}

func (c *current) onAccessElement1(t any) (any, error) {

	pattern, _ := t.(string)
	return accessElement{pattern: pattern}, nil
}

func (p *parser) callonAccessElement1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAccessElement1(stack["t"])
}

func (c *current) onAccessPattern1() (any, error) {

	text := string(c.text)
	return text, nil
}

func (p *parser) callonAccessPattern1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAccessPattern1()
}

func (c *current) onText1() (any, error) {

	text := string(c.text)
	return text, nil
}

func (p *parser) callonText1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onText1()
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expresssions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//	input := "input"
//	stats := Stats{}
//	_, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//	if err != nil {
//	    log.Panicln(err)
//	}
//	b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//	if err != nil {
//	    log.Panicln(err)
//	}
//	fmt.Println(string(b))
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i any, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (any, error) {
	b, err := io.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (any, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return strconv.Itoa(p.line) + ":" + strconv.Itoa(p.col) + " [" + strconv.Itoa(p.offset) + "]"
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]any

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        any
}

type choiceExpr struct {
	pos          position
	alternatives []any
}

type actionExpr struct {
	pos  position
	expr any
	run  func(*parser) (any, error)
}

type recoveryExpr struct {
	pos          position
	expr         any
	recoverExpr  any
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []any
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  any
}

type expr struct {
	pos  position
	expr any
}

type (
	andExpr        expr
	notExpr        expr
	zeroOrOneExpr  expr
	zeroOrMoreExpr expr
	oneOrMoreExpr  expr
)

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
	want       string
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   any
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[any]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]any
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]any
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]any)
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr any) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]any, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) printIndent(mark string, s string) string {
	return p.print(strings.Repeat(" ", p.depth)+mark, s)
}

func (p *parser) in(s string) string {
	res := p.printIndent(">", s)
	p.depth++
	return res
}

func (p *parser) out(s string) string {
	p.depth--
	return p.printIndent("<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() any
}

var statePool = &sync.Pool{
	New: func() any { return make(storeDict) },
}

func (sd storeDict) Discard() {
	for k := range sd {
		delete(sd, k)
	}
	statePool.Put(sd)
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := statePool.Get().(storeDict)
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state.Discard()
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node any) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node any, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[any]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[any]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val any, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRuleWrap(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return strings.Join(list[:len(list)-1], sep) + " " + lastSep + " " + list[len(list)-1]
	}
}

func (p *parser) parseRuleMemoize(rule *rule) (any, bool) {
	res, ok := p.getMemoized(rule)
	if ok {
		p.restore(res.end)
		return res.v, res.b
	}

	startMark := p.pt
	val, ok := p.parseRule(rule)
	p.setMemoized(startMark, rule, resultTuple{val, ok, p.pt})

	return val, ok
}

func (p *parser) parseRuleWrap(rule *rule) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}
	var (
		val       any
		ok        bool
		startMark = p.pt
	)

	if p.memoize {
		val, ok = p.parseRuleMemoize(rule)
	} else {
		val, ok = p.parseRule(rule)
	}

	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(startMark)))
	}
	return val, ok
}

func (p *parser) parseRule(rule *rule) (any, bool) {
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExprWrap(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	return val, ok
}

func (p *parser) parseExprWrap(expr any) (any, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	val, ok := p.parseExpr(expr)

	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr any) (any, bool) {
	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val any
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExprWrap(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExprWrap(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExprWrap(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExprWrap(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, lit.want)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, lit.want)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExprWrap(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExprWrap(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRuleWrap(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]any, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExprWrap(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExprWrap(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExprWrap(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
